### ISSUE TITLE
Make use of Button component

### ISSUE THREAD

**Issue by simonsmith** [giuseppeg/suitcss-components-form#1]
Think it might be worth reusing that component here?

**Comment by giuseppeg** [comment]
I don't want to tight couple the two components. As I see it `Button` is a nested component.

``` html
<span class="Form-button">
  <button class="Button">submit</button>
</span>
```

People should feel free to style buttons as they please, I just want to make sure that the `button` height, border and border radii match the `input` ones.

**Comment by simonsmith** [comment]
Yeah, fair enough.

Perhaps that could be `Form-wrapButton` as per [the doc recommendations](https://github.com/suitcss/suit/blob/master/doc/components.md#styling-dependencies).

**Comment by giuseppeg** [comment]
Ah good one!
At this point then I wonder if it is valid to style the nested component (this is the simplest solution when using partials) or attaching to the nested component (`.Excerpt-button` in the example).

**Comment by simonsmith** [comment]
Interesting yeah. I suppose by attaching a class to the button the user of the Form component can decide to opt in to the styles provided. Might make it more flexible. On the downside, they must remember to attach it.

**Comment by giuseppeg** [comment]
<blockquote>On the downside, they must remember to attach it.</blockquote>

That's not a problem I guess. From my experience it can be challenging to "mutate" existing components that were poorly designed. I am taking about html partials (not css) that are not configurable.

That said, I will definitely fix this and opt for one of the suggested solutions ;)

**Comment by giuseppeg** [comment]
I decided to stick with the `.Form-wrapButton > button` solution.
I think that it is the best in terms of composability.

See: https://github.com/giuseppeg/suitcss-components-form/commit/16f87b78b07736d5cdb08d6a7f3ded98d4734591
